# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "ccls-common_lib"
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = "2013-12-03"
  s.description = "CCLS Common Lib gem"
  s.email = "github@jakewendt.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/ccls-common_lib.rb",
    "lib/common_lib.rb",
    "lib/common_lib/action_controller_extension.rb",
    "lib/common_lib/action_controller_extension/accessible_via_protocol.rb",
    "lib/common_lib/action_controller_extension/accessible_via_user.rb",
    "lib/common_lib/action_controller_extension/routing.rb",
    "lib/common_lib/action_controller_extension/test_case.rb",
    "lib/common_lib/action_view_extension.rb",
    "lib/common_lib/action_view_extension/base.rb",
    "lib/common_lib/action_view_extension/form_builder.rb",
    "lib/common_lib/active_model.rb",
    "lib/common_lib/active_model/errors.rb",
    "lib/common_lib/active_model/validations/absence.rb",
    "lib/common_lib/active_model/validations/complete_date.rb",
    "lib/common_lib/active_model/validations/past_date.rb",
    "lib/common_lib/active_record.rb",
    "lib/common_lib/active_record/base.rb",
    "lib/common_lib/active_support_extension.rb",
    "lib/common_lib/active_support_extension/assertions.rb",
    "lib/common_lib/active_support_extension/associations.rb",
    "lib/common_lib/active_support_extension/attributes.rb",
    "lib/common_lib/active_support_extension/pending.rb",
    "lib/common_lib/active_support_extension/test_case.rb",
    "lib/common_lib/railtie.rb",
    "lib/common_lib/ruby.rb",
    "lib/common_lib/ruby/array.rb",
    "lib/common_lib/ruby/fixnum.rb",
    "lib/common_lib/ruby/hash.rb",
    "lib/common_lib/ruby/integer.rb",
    "lib/common_lib/ruby/nil_class.rb",
    "lib/common_lib/ruby/numeric.rb",
    "lib/common_lib/ruby/object.rb",
    "lib/common_lib/ruby/string.rb",
    "lib/common_lib/translation_table.rb",
    "lib/tasks/common_lib.rake",
    "lib/tasks/csv.rake",
    "lib/tasks/database.rake",
    "lib/tasks/rcov.rake",
    "vendor/assets/javascripts/common_lib.js",
    "vendor/assets/stylesheets/common_lib.css"
  ]
  s.homepage = "http://github.com/ccls/common_lib"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "CCLS Common Lib gem"
end

