-
  :attributes:
  - :title
  - :user
  - :owner_id
  :presence: true
-
  :attributes: :title
  :length:
    :minimum: 5
  :allow_blank: true
-
  :attributes: :title
  :uniqueness: true
-
  :attribute: :limited_value
  :inclusion:
    :in: <%= %w( apples oranges ) %>
  :allow_nil: true
