-
  :attribute: :name
  :presence: true
  :uniqueness: true
  :length:
    :in: !ruby/range 5..250
-
  :attribute: :zip_code
  :presence: true
  :length:
    :is: 5
-
  :attribute: :birthday
  :complete_date:
    :allow_nil: true
  :past_date: true
-
  :attribute: :other_date
  :past_date:
    :allow_today: false
    :allow_blank: true

# http://stackoverflow.com/questions/3337020/how-to-specify-ranges-in-yaml

#	http://codereview.stackexchange.com/questions/159/use-of-a-regex-stored-inside-yaml-file
#	  email_regex: !ruby/regexp '/^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i'
#
#	add a user email address and try this 
-
  :attribute: :email
  :format:
    :with: !ruby/regexp '/\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i'
#    :with: !ruby/regexp '/^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i'
  :allow_blank: true
